version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
    commands:
      - echo 'Php Install'
    
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Logging in to Amazon ECR ...'
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 194722430882.dkr.ecr.ap-south-1.amazonaws.com
    
  build:
    on-failure: ABORT
    commands: 
      - echo 'Building Images..'
      - cp .env.prod .env
      - docker build -t oredoo-blog .
      - docker tag oredoo-blog:latest 194722430882.dkr.ecr.ap-south-1.amazonaws.com/oredoo-blog:latest
    
  post_build:
    on-failure: ABORT
    commands:
      - echo 'Building Docker images'
      - docker images ls -a
      - docker push 194722430882.dkr.ecr.ap-south-1.amazonaws.com/oredoo-blog:latest